package singleton;

/**
 * @author Yugo
 */
public class CaldeiraWindow extends javax.swing.JFrame {

    private Caldeira caldeira = Caldeira.getInstancia();
    
    /**
     * Creates new form CaldeiraWindow
     */
    public CaldeiraWindow() {
        this.caldeira.iniciar(100, 50, 10, 5);
        initComponents();
        init();
    }

    private void init() {
        WindowHelper.display(this,"center");
        this.jTable_Info.getModel().setValueAt("Temperatura",0,0);
        this.jTable_Info.getModel().setValueAt(caldeira.getTemperaturaMax(),0,1);
        this.jTable_Info.getModel().setValueAt(caldeira.getTemperaturaMin(),0,2);
        this.jTable_Info.getModel().setValueAt(caldeira.getTemperaturaCorrente(),0,3);
        this.jTable_Info.getModel().setValueAt("Nivel de Agua",1,0);
        this.jTable_Info.getModel().setValueAt(caldeira.getNivelMax(),1,1);
        this.jTable_Info.getModel().setValueAt(caldeira.getNivelMin(),1,2);
        this.jTable_Info.getModel().setValueAt(caldeira.getNivelCorrente(),1,3);
        this.jTable_Info.setRowHeight(50);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Info = new javax.swing.JTable();
        jButton_Controle_Temp = new javax.swing.JButton();
        jButton_Controle_Nivel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_Info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                " ", "Maximo", "Minimo", "Atual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Info.setToolTipText("");
        jScrollPane1.setViewportView(jTable_Info);

        jButton_Controle_Temp.setText("Controle de Temperatura");
        jButton_Controle_Temp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Controle_TempMouseClicked(evt);
            }
        });
        jButton_Controle_Temp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Controle_TempActionPerformed(evt);
            }
        });

        jButton_Controle_Nivel.setText("Controle de Nivel");
        jButton_Controle_Nivel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Controle_NivelMouseClicked(evt);
            }
        });
        jButton_Controle_Nivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Controle_NivelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Controle_Temp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Controle_Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Controle_Temp)
                    .addComponent(jButton_Controle_Nivel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Controle_TempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Controle_TempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Controle_TempActionPerformed

    private void jButton_Controle_NivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Controle_NivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Controle_NivelActionPerformed

    private void jButton_Controle_TempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Controle_TempMouseClicked
        TemperaturaWindow.main(null);
        jButton_Controle_Temp.setEnabled(false);
    }//GEN-LAST:event_jButton_Controle_TempMouseClicked

    private void jButton_Controle_NivelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Controle_NivelMouseClicked
        NivelWindow.main(null);
        jButton_Controle_Nivel.setEnabled(false);
    }//GEN-LAST:event_jButton_Controle_NivelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaldeiraWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaldeiraWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaldeiraWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaldeiraWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaldeiraWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Controle_Nivel;
    private javax.swing.JButton jButton_Controle_Temp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Info;
    // End of variables declaration//GEN-END:variables
}
