package singleton;

import java.util.Observable;
import java.util.Observer;
import javax.swing.JTable;
import java.text.DecimalFormat;

/**
 * @author Yugo
 */
public class CaldeiraWindow extends javax.swing.JFrame implements Observer {

    private final Caldeira caldeira = Caldeira.getInstancia();
    private final Notificacao noticacao = new Notificacao(); 
    
    /**
     * Creates new form CaldeiraWindow
     */
    public CaldeiraWindow() {
        this.caldeira.iniciar(200, 100, 50, 25);
        initComponents();
        init();
    }

    private void init() {
        TemperaturaWindow.main(null);
        NivelWindow.main(null);
        
        caldeira.addObserver(this);
        WindowHelper.display(this,"center");
        this.jTable_Info.getModel().setValueAt(caldeira.getTemperaturaMax(),0,1);
        this.jTable_Info.getModel().setValueAt(caldeira.getTemperaturaMin(),0,2);
        this.jTable_Info.getModel().setValueAt(caldeira.getTemperaturaCorrente(),0,3);
        this.jTable_Info.getModel().setValueAt(caldeira.getNivelMax(),1,1);
        this.jTable_Info.getModel().setValueAt(caldeira.getNivelMin(),1,2);
        this.jTable_Info.getModel().setValueAt(caldeira.getNivelCorrente(),1,3);
        this.jTable_Info.setRowHeight(50);
        this.jTextArea_Notify.setEditable(false);
    }
    
    private void checkNotify(){
        String log_error="";
        if (caldeira.getNivelCorrente() < caldeira.getNivelMin()) {
            log_error += noticacao.nivelBaixo()+ "\n";
        }
        if (caldeira.getNivelCorrente() > caldeira.getNivelMax()) {
            log_error += noticacao.nivelAlto()+ "\n";
        }
        if (caldeira.getTemperaturaCorrente() < caldeira.getTemperaturaMin()) {
            log_error += noticacao.temperaturaBaixa()+ "\n";
        }
        if (caldeira.getTemperaturaCorrente() > caldeira.getTemperaturaMax()) {
            log_error += noticacao.temperaturaAlta()+ "\n";
            this.jLabel_Icon.setIcon(noticacao.getPoison(jLabel_Icon.getWidth(), jLabel_Icon.getHeight()));
        } 
        this.jTextArea_Notify.setText(log_error);
    }
    
    private void updateTable() { 
        JTable t = this.jTable_Info; 
        DecimalFormat df = new DecimalFormat("0.00");
        float temp = caldeira.getTemperaturaCorrente();
        float nvl = caldeira.getNivelCorrente();
        t.getModel().setValueAt(df.format(temp),0,3);
        t.getModel().setValueAt(df.format(nvl),1,3);
        checkNotify();
    }
    
    @Override
    public void update(Observable o, Object arg) {
        this.updateTable();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Info = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_Notify = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caldeira");

        jTable_Info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Temperatura", null, null, null},
                {"Nivel", null, null, null}
            },
            new String [] {
                " ", "Maximo", "Minimo", "Atual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Info.setToolTipText("");
        jScrollPane1.setViewportView(jTable_Info);

        jTextArea_Notify.setColumns(20);
        jTextArea_Notify.setRows(5);
        jScrollPane2.setViewportView(jTextArea_Notify);

        jLabel1.setText("Noticações:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane2))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel_Icon, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaldeiraWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaldeiraWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaldeiraWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaldeiraWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaldeiraWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Icon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Info;
    private javax.swing.JTextArea jTextArea_Notify;
    // End of variables declaration//GEN-END:variables
}
