package singleton;

import java.util.Observable;
import java.util.Observer;
import javax.swing.JTable;
import java.text.DecimalFormat;

/**
 * @author Yugo
 */
public class NivelWindow extends javax.swing.JFrame implements Observer {

    private final Caldeira caldeira = Caldeira.getInstancia();
    private Notificacao notificacao = new Notificacao(); 
    
    /**
     * Creates new form NivelWindow
     */
    public NivelWindow() {
        initComponents();
        init();
    }
    
    private void init() {
        caldeira.addObserver(this);
        WindowHelper.display(this,"right");
        this.jTable_Info.getModel().setValueAt(caldeira.getTemperaturaMax(),0,1);
        this.jTable_Info.getModel().setValueAt(caldeira.getTemperaturaMin(),0,2);
        this.jTable_Info.getModel().setValueAt(caldeira.getTemperaturaCorrente(),0,3);
        this.jTable_Info.getModel().setValueAt(caldeira.getNivelMax(),1,1);
        this.jTable_Info.getModel().setValueAt(caldeira.getNivelMin(),1,2);
        this.jTable_Info.getModel().setValueAt(caldeira.getNivelCorrente(),1,3);
        this.jTable_Info.setRowHeight(50);
        this.jTextArea_Notify.setEditable(false);
    }
       
    private void updateTable() { 
        JTable t = this.jTable_Info; 
        DecimalFormat df = new DecimalFormat("0.00");
        float temp = caldeira.getTemperaturaCorrente();
        float nvl = caldeira.getNivelCorrente();
        t.getModel().setValueAt(df.format(temp),0,3);
        t.getModel().setValueAt(df.format(nvl),1,3);
        this.jTextArea_Notify.setText(notificacao.checkNotify(this.jLabel_Icon));
    }
    
    @Override
    public void update(Observable o, Object arg) {
        this.updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Info = new javax.swing.JTable();
        jButton_AddAgua = new javax.swing.JButton();
        jSlider_Quantidade_Agua = new javax.swing.JSlider();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_Notify = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nivel");

        jTable_Info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Temperatura", null, null, null},
                {"Nivel", null, null, null}
            },
            new String [] {
                " ", "Maximo", "Minimo", "Atual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Info.setToolTipText("");
        jScrollPane1.setViewportView(jTable_Info);

        jButton_AddAgua.setText("Adicionar Nivel");
        jButton_AddAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddAguaActionPerformed(evt);
            }
        });

        jSlider_Quantidade_Agua.setMajorTickSpacing(2);
        jSlider_Quantidade_Agua.setMaximum(10);
        jSlider_Quantidade_Agua.setMinorTickSpacing(2);
        jSlider_Quantidade_Agua.setPaintLabels(true);
        jSlider_Quantidade_Agua.setPaintTicks(true);
        jSlider_Quantidade_Agua.setValue(5);

        jTextArea_Notify.setColumns(20);
        jTextArea_Notify.setRows(5);
        jScrollPane2.setViewportView(jTextArea_Notify);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Noticações:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSlider_Quantidade_Agua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_AddAgua, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 147, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_AddAgua)
                .addGap(18, 18, 18)
                .addComponent(jSlider_Quantidade_Agua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AddAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddAguaActionPerformed
        Caldeira cald = this.caldeira;
        cald.adicionalNivel(this.jSlider_Quantidade_Agua.getValue());
        
        //Simular a queda de temperatura ao adicionar agua
        float diff = Math.abs(cald.getTemperaturaCorrente() - cald.getNivelCorrente()) * (float)(0.2);
        this.caldeira.setTemperaturaCorrente(cald.getTemperaturaCorrente() - diff);
    }//GEN-LAST:event_jButton_AddAguaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NivelWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NivelWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NivelWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NivelWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NivelWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AddAgua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Icon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider_Quantidade_Agua;
    private javax.swing.JTable jTable_Info;
    private javax.swing.JTextArea jTextArea_Notify;
    // End of variables declaration//GEN-END:variables
}
