package singleton;

import java.util.Observable;
import java.util.Observer;
import javax.swing.JTable;
import java.text.DecimalFormat;

/**
 * @author Yugo
 */
public class TemperaturaWindow extends javax.swing.JFrame implements Observer {

    private final Caldeira caldeira = Caldeira.getInstancia();
    private final Notificacao notificacao = new Notificacao();
    
    /**
     * Creates new form TemperaturaWindow
     */
    public TemperaturaWindow() {
        initComponents();
        init();
    }

    private void init() {
        caldeira.addObserver(this);
        WindowHelper.display(this,"left");
        this.jTable_Info.getModel().setValueAt(caldeira.getTemperaturaMax(),0,1);
        this.jTable_Info.getModel().setValueAt(caldeira.getTemperaturaMin(),0,2);
        this.jTable_Info.getModel().setValueAt(caldeira.getTemperaturaCorrente(),0,3);
        this.jTable_Info.getModel().setValueAt(caldeira.getNivelMax(),1,1);
        this.jTable_Info.getModel().setValueAt(caldeira.getNivelMin(),1,2);
        this.jTable_Info.getModel().setValueAt(caldeira.getNivelCorrente(),1,3);
        this.jTable_Info.setRowHeight(50);
        this.jTextArea_Notify.setEditable(false);
    }
        
    private void updateTable() { 
        JTable t = this.jTable_Info; 
        DecimalFormat df = new DecimalFormat("0.00");
        float temp = caldeira.getTemperaturaCorrente();
        float nvl = caldeira.getNivelCorrente();
        t.getModel().setValueAt(df.format(temp),0,3);
        t.getModel().setValueAt(df.format(nvl),1,3);
        this.jTextArea_Notify.setText(notificacao.checkNotify(this.jLabel_Icon));
    }
    
    @Override
    public void update(Observable o, Object arg) {
        this.updateTable();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Info = new javax.swing.JTable();
        jSlider_Temperatura_Fonte_Calor = new javax.swing.JSlider();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_Notify = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temperatura");

        jTable_Info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Temperatura", null, null, null},
                {"Nivel", null, null, null}
            },
            new String [] {
                " ", "Maximo", "Minimo", "Atual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Info.setToolTipText("");
        jScrollPane1.setViewportView(jTable_Info);

        jSlider_Temperatura_Fonte_Calor.setMajorTickSpacing(50);
        jSlider_Temperatura_Fonte_Calor.setMaximum(300);
        jSlider_Temperatura_Fonte_Calor.setMinorTickSpacing(50);
        jSlider_Temperatura_Fonte_Calor.setPaintLabels(true);
        jSlider_Temperatura_Fonte_Calor.setPaintTicks(true);
        jSlider_Temperatura_Fonte_Calor.setToolTipText("Temperatura na fonte de calor");
        jSlider_Temperatura_Fonte_Calor.setValue(150);
        jSlider_Temperatura_Fonte_Calor.setName(""); // NOI18N
        jSlider_Temperatura_Fonte_Calor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_Temperatura_Fonte_CalorStateChanged(evt);
            }
        });

        jTextArea_Notify.setColumns(20);
        jTextArea_Notify.setRows(5);
        jScrollPane2.setViewportView(jTextArea_Notify);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Noticações:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jSlider_Temperatura_Fonte_Calor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider_Temperatura_Fonte_Calor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider_Temperatura_Fonte_CalorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_Temperatura_Fonte_CalorStateChanged
        this.caldeira.alterarTemperaturaFonteCalor(jSlider_Temperatura_Fonte_Calor.getValue());
    }//GEN-LAST:event_jSlider_Temperatura_Fonte_CalorStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TemperaturaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TemperaturaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TemperaturaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TemperaturaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TemperaturaWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Icon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider_Temperatura_Fonte_Calor;
    private javax.swing.JTable jTable_Info;
    private javax.swing.JTextArea jTextArea_Notify;
    // End of variables declaration//GEN-END:variables
}
