package singleton;

import java.util.Timer;
import java.util.TimerTask;

/**
 * @author Yugo
 */
public class TemperaturaWindow extends javax.swing.JFrame {

    private Caldeira caldeira = Caldeira.getInstancia();
    
    /**
     * Creates new form TemperaturaWindow
     */
    public TemperaturaWindow() {
        initComponents();
        init();
    }

    private void init() {
        WindowHelper.display(this,"left");
        this.jTable_Info.getModel().setValueAt("Temperatura",0,0);
        this.jTable_Info.getModel().setValueAt(caldeira.getTemperaturaMax(),0,1);
        this.jTable_Info.getModel().setValueAt(caldeira.getTemperaturaMin(),0,2);
        this.jTable_Info.getModel().setValueAt(caldeira.getTemperaturaCorrente(),0,3);
        this.jTable_Info.getModel().setValueAt("Nivel de Agua",1,0);
        this.jTable_Info.getModel().setValueAt(caldeira.getNivelMax(),1,1);
        this.jTable_Info.getModel().setValueAt(caldeira.getNivelMin(),1,2);
        this.jTable_Info.getModel().setValueAt(caldeira.getNivelCorrente(),1,3);
        this.jTable_Info.setRowHeight(50);
        WindowHelper.addTable(this.jTable_Info);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Info = new javax.swing.JTable();
        jSlider_Temperatura_Fonte_Calor = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temperatura");

        jTable_Info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                " ", "Maximo", "Minimo", "Atual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Info.setToolTipText("");
        jScrollPane1.setViewportView(jTable_Info);

        jSlider_Temperatura_Fonte_Calor.setMajorTickSpacing(10);
        jSlider_Temperatura_Fonte_Calor.setPaintLabels(true);
        jSlider_Temperatura_Fonte_Calor.setToolTipText("Temperatura na fonte de calor");
        jSlider_Temperatura_Fonte_Calor.setName(""); // NOI18N
        jSlider_Temperatura_Fonte_Calor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider_Temperatura_Fonte_CalorStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSlider_Temperatura_Fonte_Calor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jSlider_Temperatura_Fonte_Calor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider_Temperatura_Fonte_CalorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider_Temperatura_Fonte_CalorStateChanged
        this.caldeira.alterarTemperaturaFonteCalor(jSlider_Temperatura_Fonte_Calor.getValue());
    }//GEN-LAST:event_jSlider_Temperatura_Fonte_CalorStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TemperaturaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TemperaturaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TemperaturaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TemperaturaWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TemperaturaWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider_Temperatura_Fonte_Calor;
    private javax.swing.JTable jTable_Info;
    // End of variables declaration//GEN-END:variables
}
